Helper/RockShop/RockShop/Areas/Admin/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RockShop.Areas.Admin.ViewModels.Auth;
using RockShop.Properties;
using RockShop.Services;
using System.Threading.Tasks;

namespace RockShop.Areas.Admin.Controllers
{
    /// <summary>
    /// Авторизация
    /// </summary>
    [Area("Admin")]
    public class AuthController : Controller
    {
        private readonly IAuthService authService;

        public AuthController(IAuthService authService)
        {
            this.authService = authService;
        }

        [HttpGet]
        public IActionResult Login() => View();

        /// <summary>
        /// Обрабокта входа
        /// </summary>
        /// <param name="loginModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login([FromForm] LoginModel loginModel)
        {
            if (!ModelState.IsValid)
                return View("Login", loginModel);

            if (!await authService.LoginAsync(loginModel.Login, loginModel.Password))
            {
                ModelState.AddModelError(string.Empty, Resource.LoginIncorrect);
                return View("Login", loginModel);
            }

            return RedirectToAction("Index", "Users");
        }

        /// <summary>
        /// Выход
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await authService.LogoutAsync();
            return RedirectToAction("Login");
        }
    }
}

Helper/RockShop/RockShop/Areas/Admin/Controllers/RocksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RockShop.Areas.Admin.ViewModels.Rocks;
using RockShop.Data.Models;
using RockShop.Extensions;
using RockShop.Services;
using System;
using System.Threading.Tasks;

namespace RockShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class RocksController : Controller
    {
        private readonly IRockService rockService;

        public RocksController(IRockService rockService)
        {
            this.rockService = rockService;
        }

        // GET: Rocks
        public async Task<IActionResult> Index()
        {
            return View(await rockService.GetRocksAsync());
        }

        // GET: Rocks/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rock = await rockService.GetRockByIdAsync(id.Value);
            if (rock == null)
            {
                return NotFound();
            }

            return View(rock);
        }

        // GET: Rocks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rocks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] CreateRockRequest rock)
        {
            if (ModelState.IsValid)
            {
                await rockService.CreateRockAsync(new Rock
                {
                    Description = rock.Description,
                    Name = rock.Name,
                    Price = rock.Price,
                    Image = Convert.ToBase64String(await rock.Image.OpenReadStream().ToByteArrayAsync())
                });
                return RedirectToAction(nameof(Index));
            }

            return View(new Rock
            {
                Description = rock.Description,
                Name = rock.Name,
                Price = rock.Price
            });
        }

        // GET: Rocks/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rock = await rockService.GetRockByIdAsync(id.Value);
            if (rock == null)
            {
                return NotFound();
            }

            return View(rock);
        }

        // POST: Rocks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [FromForm] EditRockRequest rock)
        {
            if (id != rock.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string image = null;
                    if (rock.Image != null)
                        image = Convert.ToBase64String(await rock.Image.OpenReadStream().ToByteArrayAsync());

                    await rockService.UpdateRockAsync(new Rock
                    {
                        Id = id,
                        Description = rock.Description,
                        Name = rock.Name,
                        Price = rock.Price,
                        Image = image,
                        CreationDateTime = rock.CreationDateTime
                    });
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await rockService.RockExistsAsync(rock.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(new Rock
            {
                Id = id,
                Description = rock.Description,
                Name = rock.Name,
                Price = rock.Price,
                Image = rock.CurrentImage,
                CreationDateTime = rock.CreationDateTime
            });
        }

        // GET: Rocks/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rock = await rockService.GetRockByIdAsync(id.Value);
            if (rock == null)
            {
                return NotFound();
            }

            return View(rock);
        }

        // POST: Rocks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            await rockService.DeleteRockAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Helper/RockShop/RockShop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using RockShop.Models;
using RockShop.Services;
using System.Threading.Tasks;

namespace RockShop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService orderService;

        public OrderController(IOrderService orderService)
        {
            this.orderService = orderService;
        }

        public async Task<IActionResult> CreateOrder([FromForm] CreateOrderRequest createOrderRequest)
        {
            TempData["Message"] = RockShop.Properties.Resource.OrderCreated;
            TempData["MessageType"] = "success";

            if (!await orderService.AddOrderAsync(createOrderRequest.OrderId, createOrderRequest.OrderCount))
            {
                TempData["Message"] = RockShop.Properties.Resource.OrderCreateError;
                TempData["MessageType"] = "error";
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

Helper/RockShop/RockShop/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @RockShop.Properties.Resource.ApplicationName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@RockShop.Properties.Resource.ApplicationName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@RockShop.Properties.Resource.Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Users" asp-action="Index">@RockShop.Properties.Resource.User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Rocks" asp-action="Index">@RockShop.Properties.Resource.Rock</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Order" asp-action="Index">@RockShop.Properties.Resource.Orders</a>
                            </li>

                            <li class="nav-item">
                                <a class="btn btn-info" asp-area="Admin" asp-controller="Auth" asp-action="Logout">@RockShop.Properties.Resource.Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @RockShop.Properties.Resource.ApplicationName
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>