Helper/PeopleAnalysis/PeopleAnalysis/Controllers/ObjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PeopleAnalysis.ApplicationAPI;

namespace PeopleAnalysis.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ObjectsController : Controller
    {
        private readonly IApplicationAPIClient applicationAPIClient;

        public ObjectsController(IApplicationAPIClient applicationAPIClient)
        {
            this.applicationAPIClient = applicationAPIClient;
        }

        // GET: AnalysObjects
        public async Task<IActionResult> Index()
        {
            return View(await applicationAPIClient.ApiObjectsAsync());
        }

        // GET: AnalysObjects/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AnalysObject analysObject)
        {
            if (ModelState.IsValid)
            {
                await applicationAPIClient.ApiObjectsCreateAsync(analysObject);
                return RedirectToAction(nameof(Index));
            }
            return View(analysObject);
        }

        // GET: AnalysObjects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var analysObject = await applicationAPIClient.ApiObjectsFindAsync(id);
            if (analysObject == null)
            {
                return NotFound();
            }
            return View(analysObject);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, AnalysObject analysObject)
        {
            if (id != analysObject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await applicationAPIClient.ApiObjectsEditAsync(id, analysObject);
                }
                catch (Exception)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(analysObject);
        }

        // POST: AnalysObjects/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await applicationAPIClient.ApiObjectsDeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Helper/PeopleAnalysis/PeopleAnalysis/Controllers/RequestController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PeopleAnalysis.ApplicationAPI;
using PeopleAnalysis.Extensions;
using PeopleAnalysis.Models;
using PeopleAnalysis.Services;

namespace PeopleAnalysis.Controllers
{
    [Authorize]
    public class RequestController : Controller
    {
        private readonly IApplicationAPIClient applicationAPIClient;

        public RequestController(IApplicationAPIClient applicationAPIClient)
        {
            this.applicationAPIClient = applicationAPIClient;
        }

        public async Task<IActionResult> Index()
        {
            List<Request> requests = new List<Request>();
            IEnumerable<Request> request = await applicationAPIClient.ApiRequestGetAsync();
            if (!User.IsAdmin())
                request = request.Where(x => x.OwnerId == User.UserId());
            foreach (var r in request.AsEnumerable().GroupBy(x => new { x.UserId, x.Social, x.OwnerId }).ToDictionary(x => x.Key, x => x.OrderBy(x => x.DateTime)))
            {
                var res = r.Value.Last();
                res.DateTime = r.Value.First().DateTime;
                requests.Add(res);
            }
            return View(requests);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromForm]int toDelete)
        {
            await applicationAPIClient.ApiRequestPostAsync(toDelete);
            return Redirect("Index");
        }
    }
}

Helper/PeopleAnalysis/PeopleAnalysis/Controllers/UsersController.cs
using System.Linq;
using System.Threading.Tasks;
using CommonCoreLibrary.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PeopleAnalysis.AuthAPI;

namespace PeopleAnalysis.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly IAuthAPIClient authAPIClient;

        public UsersController(IAuthAPIClient authAPIClient)
        {
            this.authAPIClient = authAPIClient;
        }

        // GET: LoginViewModels
        public async Task<IActionResult> Index()
        {
            return View(await authAPIClient.ApiUsersAsync());
        }

        // GET: LoginViewModels/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(UserViewModel loginViewModel)
        {
            if (ModelState.IsValid)
            {
                await authAPIClient.ApiUsersCreateAsync(loginViewModel);
                return RedirectToAction(nameof(Index));
            }
            return View(loginViewModel);
        }

        // GET: LoginViewModels/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
                return NotFound();
            return View(await authAPIClient.ApiUsersFindAsync(id));
        }

        [HttpPost]

        public async Task<IActionResult> Edit(string id, UserViewModel loginViewModel)
        {
            if (id != loginViewModel.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                await authAPIClient.ApiUsersEditAsync(id, loginViewModel);
                return RedirectToAction(nameof(Index));
            }
            return View(loginViewModel);
        }

        // POST: LoginViewModels/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed([FromForm]string toDelete)
        {
            await authAPIClient.ApiUsersDeleteAsync(toDelete);
            return RedirectToAction(nameof(Index));
        }
    }
}

Helper/PeopleAnalysis/PeopleAnalysis/Views/Shared/_Layout.cshtml
@inject CommonCoreLibrary.Services.ILocalizer localizer
@{
    if (User.Identity.IsAuthenticated)
        System.Threading.Thread.CurrentThread.CurrentUICulture = new System.Globalization.CultureInfo(User.UICode());
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PeopleAnalysis</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/lightbox2/css/lightbox.min.css" />
    <link rel="stylesheet" href="~/lib/Chart.js/Chart.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PeopleAnalysis</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@localizer["Home"]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="Index">@localizer["Requests"]</a>
                            </li>
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">@localizer["Users"]</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Objects" asp-action="Index">@localizer["Objects"]</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PeopleAnalysis - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/lightbox2/js/lightbox.min.js"></script>
    <script src="~/lib/Chart.js/Chart.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>