Helper/SiteCarAsp/SiteCarAsp/Controllers/CarController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SiteCarAsp.Services;
using SiteCarAsp.ViewModels;

namespace SiteCarAsp.Controllers
{
    /// <summary>
    /// Контроллер для машин
    /// </summary>
    public class CarController : Controller
    {
        /// <summary>
        /// Сервис машин
        /// </summary>
        private readonly ICarService carService;

        public CarController(ICarService carService)
        {
            this.carService = carService;
        }

        /// <summary>
        /// Страница все машины
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Index() => View(new CarInformationViewModel(await carService.GetCars()));

        /// <summary>
        /// Render страницы при запросе фильтрации
        /// </summary>
        /// <param name="filters"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> FilterCars([FromBody] FilterViewModel[] filters)
        {
            return PartialView("~/Views/Components/CarTable.partial.cshtml", await carService.GetFilteredCars(filters));
        }


        [HttpGet]
        public async Task<IActionResult> UsedCars() => View("Index", new CarInformationViewModel(await carService.GetUsedCars()) { ActiveFilters = new[] { new FilterViewModel { Field = "used", Val = "true" } } });
        [HttpGet]
        public async Task<IActionResult> NewCars() => View("Index", new CarInformationViewModel(await carService.GetNewCars()) { ActiveFilters = new[] { new FilterViewModel { Field = "used", Val = "false" } } });
    }
}

Helper/SiteCarAsp/SiteCarAsp/Controllers/CreditsController.cs
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SiteCarAsp.Models;
using SiteCarAsp.Services.Controller;
using SiteCarAsp.ViewModels;
using SiteCarAsp.ViewModels.Request;

namespace SiteCarAsp.Controllers
{
    /// <summary>
    /// Контроллер для кредитов
    /// </summary>
    public class CreditsController : Controller
    {
        /// <summary>
        /// Сервис для кредитов
        /// </summary>
        private readonly ICreditsService creditsService;
        private readonly IMapper mapper;

        public CreditsController(ICreditsService creditsService, IMapper mapper)
        {
            this.creditsService = creditsService;
            this.mapper = mapper;
        }

        /// <summary>
        /// Получить основную Viewху
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Index() => View(new CreditsViewModel { CarInformations = await creditsService.GetCarsAsync() });

        /// <summary>
        /// Создать запрос на кредит
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Create([FromForm] CreateCreditRequest createCreditRequest)
        {
            if (!ModelState.IsValid)
            {
                var model = mapper.Map<CreditsViewModel>(createCreditRequest);
                model.CarInformations = await creditsService.GetCarsAsync();
                return View("Index", model);
            }

            await creditsService.AddAsync(mapper.Map<Credit>(createCreditRequest));

            return RedirectToAction("Index");
        }
    }
}

Helper/SiteCarAsp/SiteCarAsp/Controllers/TestDriveController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SiteCarAsp.Models;
using SiteCarAsp.Services;
using SiteCarAsp.ViewModels;
using SiteCarAsp.ViewModels.Request;
using System.Threading.Tasks;

namespace SiteCarAsp.Controllers
{
    /// <summary>
    /// Контроллер для TestDrive
    /// </summary>
    public class TestDriveController : Controller
    {
        private readonly ITestDriveService testDriveService;
        private readonly IMapper mapper;

        public TestDriveController(ITestDriveService testDriveService, IMapper mapper)
        {
            this.testDriveService = testDriveService;
            this.mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] int carId) => View(new TestDriveViewModel { CarId = carId, CarInformations = await testDriveService.GetCarsAsync() });

        [HttpPost]
        public async Task<IActionResult> Create([FromForm] CreateTestDriveRequest createTestDrive)
        {
            if (!ModelState.IsValid)
            {
                var model = mapper.Map<TestDriveViewModel>(createTestDrive);
                model.CarInformations = await testDriveService.GetCarsAsync();
                return View("Index", model);
            }
            await testDriveService.AddTestDriveAsync(mapper.Map<TestDrive>(createTestDrive));
            return RedirectToAction("Index");
        }
    }
}

Helper/SiteCarAsp/SiteCarAsp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SiteCarAsp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/cards/css/cards.css" />
    <link rel="stylesheet" href="~/lib/slick-carousel/slick.min.css" />
    <link rel="stylesheet" href="~/lib/slick-carousel/slick-theme.min.css" />
    <link rel="stylesheet" href="~/css/index.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="@Url.Action("Index","Car")"><img src="~/img/icon.svg" /></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Car")">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("NewCars","Car")">New cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("UsedCars","Car")">Used cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","TestDrive")">Test drive</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Credits")">Credits</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("AboutUs","Home")">About us and Contacts</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    @RenderBody()

    <footer class="border-top footer text-muted">
        <p class="text-center w-100">
            © 2019-@DateTime.Today.Year OOO "Test Drive"
        </p>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/slick-carousel/slick.min.js"></script>
    <script src="~/lib/cards/js/cards.js"></script>
    <script src="~/js/filter.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>